const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const todayISO=()=>new Date().toISOString().slice(0,10);
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const db={get(k,d){return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
function seed(){if(db.get('seeded',false))return;db.set('lifestyles',[{id:'l1',name:'工作',color:'#2563eb'},{id:'l2',name:'學習',color:'#22c55e'},{id:'l3',name:'運動',color:'#f59e0b'},{id:'l4',name:'健康',color:'#a855f7'},{id:'l5',name:'休閒娛樂',color:'#fb7185'},{id:'l6',name:'家庭',color:'#f97316'},{id:'l7',name:'社交',color:'#64748b'},{id:'l8',name:'其他',color:'#94a3b8'}]); const d=todayISO(); db.set('tasks',[{id:uid(),title:'數學練習題',importance:5,lifestyleId:'l2',startAt:d+'T09:00',endAt:d+'T10:30',note:'備註',completed:false,subtasks:[{id:uid(),title:'完成第 1-10 題',done:true},{id:uid(),title:'完成第 11-20 題',done:false}]},{id:uid(),title:'英文單字複習',importance:4,lifestyleId:'l2',startAt:d+'T11:00',endAt:d+'T12:00',note:'備註',completed:false,subtasks:[{id:uid(),title:'複習 Unit 1-3',done:false},{id:uid(),title:'完成單字測驗',done:false}]},{id:uid(),title:'閱讀課外書',importance:3,lifestyleId:'l5',startAt:d+'T20:00',endAt:d+'T21:00',note:'',completed:false,subtasks:[{id:uid(),title:'閱讀 30 頁',done:false}]}]);db.set('records',[]);db.set('seeded',true)}
seed();
function life(id){return db.get('lifestyles',[]).find(x=>x.id===id)||{name:'已刪除',color:'#94a3b8'}}
function fmtDate(d=todayISO()){let n=new Date(d);return `${n.getFullYear()}.${String(n.getMonth()+1).padStart(2,'0')}.${String(n.getDate()).padStart(2,'0')}`}
function weekday(d=todayISO()){return '星期'+'日一二三四五六'[new Date(d).getDay()]}
function pct(date=todayISO()){let tasks=db.get('tasks',[]).filter(t=>!t.deleted&&t.startAt.slice(0,10)<=date&&t.endAt.slice(0,10)>=date); if(!tasks.length)return 0; return Math.round(tasks.filter(t=>taskDone(t)).length/tasks.length*100)}
function taskDone(t){return t.completed || (t.subtasks&&t.subtasks.length&&t.subtasks.every(s=>s.done))}
function topbar(title=''){let p=pct(todayISO());return `<div class="topbar"><button class="iconbtn" onclick="openMenu()">☰</button><div class="datebox"><div class="calico">▣</div><div><div class="date-main">${fmtDate()}</div><div class="weekday">${weekday()}</div></div></div><div><div class="ring" style="--p:${p}%"><span>${p}%</span></div><div class="small" style="text-align:center">今日完成率</div></div></div>${menuHTML()}`}
function menuHTML(){return `<div class="menu-panel" id="menu"><div class="menu-card"><div class="menu-head"><button class="iconbtn close" onclick="closeMenu()">×</button>目錄</div><a class="menu-item" href="today.html"><span>☑</span>今日任務<span class="arrow">›</span></a><a class="menu-item" href="task-form.html"><span>⊞</span>新增事項<span class="arrow">›</span></a><a class="menu-item" href="calendar.html"><span>▣</span>月曆<span class="arrow">›</span></a><a class="menu-item" href="time-records.html"><span>◷</span>時間記錄區<span class="arrow">›</span></a><a class="menu-item" href="search.html"><span>⌕</span>搜索<span class="arrow">›</span></a></div></div>`}
function openMenu(){$('#menu').style.display='block'} function closeMenu(){$('#menu').style.display='none'}
function minutes(a,b){return Math.max(0,Math.round((new Date(b)-new Date(a))/60000))}
function timeRange(t){return `${t.startAt.slice(11,16)} - ${t.endAt.slice(11,16)}`}
function saveTask(payload){let tasks=db.get('tasks',[]); if(payload.id){let i=tasks.findIndex(t=>t.id===payload.id);tasks[i]=payload}else tasks.push({...payload,id:uid(),completed:false}); db.set('tasks',tasks)}
function deleteTask(id){let tasks=db.get('tasks',[]).map(t=>t.id===id?{...t,deleted:true}:t);db.set('tasks',tasks)}
function modal(id,show=true){$(id).style.display=show?'grid':'none'}
window.openMenu=openMenu;window.closeMenu=closeMenu;window.db=db;window.life=life;window.topbar=topbar;window.uid=uid;window.todayISO=todayISO;window.taskDone=taskDone;window.saveTask=saveTask;window.deleteTask=deleteTask;window.minutes=minutes;window.timeRange=timeRange;window.modal=modal;
