CREATE DATABASE IF NOT EXISTS autonomous_learning CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE autonomous_learning;
CREATE TABLE users(id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(50),email VARCHAR(120),created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE lifestyles(id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT DEFAULT 1,name VARCHAR(20) NOT NULL,color_hex CHAR(7) NOT NULL,sort_order INT DEFAULT 0,is_deleted TINYINT DEFAULT 0,deleted_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE tasks(id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT DEFAULT 1,lifestyle_id BIGINT,title VARCHAR(50) NOT NULL,importance TINYINT NOT NULL,start_at DATETIME NOT NULL,end_at DATETIME NOT NULL,estimated_minutes INT DEFAULT 0,note VARCHAR(200),completed_at DATETIME NULL,is_deleted TINYINT DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE subtasks(id BIGINT PRIMARY KEY AUTO_INCREMENT,task_id BIGINT,title VARCHAR(50),sort_order INT DEFAULT 0,is_completed TINYINT DEFAULT 0,completed_at DATETIME NULL);
CREATE TABLE time_entries(id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT DEFAULT 1,task_id BIGINT NULL,lifestyle_id BIGINT,activity_name VARCHAR(100),start_at DATETIME,end_at DATETIME,meaning_score TINYINT,happiness_score TINYINT,note VARCHAR(200),is_deleted TINYINT DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
